### ISSUE TITLE
`console` should always be visible

### ISSUE THREAD

**Issue by terinjokes** [whatwg/console#2]
Add language that ensures that `console` is always visible and usable to scripts, even if the developer console has not been opened or does not exist.

**Comment by domenic** [comment]
This comes automatically with the spec definitions, but adding a `<p class="note">` would probably be a good idea.

It might also be worth adding a sentence or two to the Printer() section to say something like "if the console is not open, implementations may choose to buffer messages to show in the future, or may discard the messages entirely."

**Comment by terinjokes** [comment]
I think that sentence works well.

**Comment by robertkowalski** [comment]
I guess we would also change the IDL part from

```
[NoInterfaceObject]
interface Console {

[...]
```

```
[NoInterfaceObject, Exposed=(Window,Worker)]
interface Console {

[...]
```

**Comment by domenic** [comment]
Right now exposed-everywhere is implied. But yeah, being explicit is generally a good idea, and @annevk encourages us to do so for new specs. You'll want to include ServiceWorker too I think; @annevk are those three the total set?

**Comment by annevk** [comment]
If you do `Window,Worker` you are everywhere. `ServiceWorker` is part of `Worker`.

**Comment by robertkowalski** [comment]
> It might also be worth adding a sentence or two to the Printer() section to say something like "if the console is not open, implementations may choose to buffer messages to show in the future, or may discard the messages entirely."

I wonder if there are implementations which do not buffer the output.

As a developer I rely on the behaviour that browsers buffer the output, example:

I sometimes have to debug Selenium tests, where a testrunner goes to a certain page / section and then fails, usually because of bad timing / race conditions. I can't stress enough how useful it is that the browsers are buffering the output from the console for me, so that I can open the console afterwards. The same behaviour also comes handy when I forgot to open the console in other day-to-day work.

1. I am curious if there are implementations out there which discard the output?
2. I feel unsure if this is more a implementation detail and UX improvement on the implementor side, or something people should be able to rely on... i personally was relying on this behaviour in the past as developer (see my example) - what do you think?

**Comment by domenic** [comment]
Maybe it would be a good "should" instead of "must" requirement... hmm. Maybe must is OK though if that's what everyone does? I kind of doubt they all have infinite buffers though, so the language might need to be kind of loose.

**Comment by bgrins** [comment]
> Maybe must is OK though if that's what everyone does? I kind of doubt they all have infinite buffers though, so the language might need to be kind of loose.

FWIW at least in Firefox we buffer the last 200 messages to display in a yet-to-be-opened console.  If the console is already opened, then there's a larger cap on how many we show in the frontend.

**Comment by robertkowalski** [comment]
agree with the infinite buffers, infinite buffers would be fun :smile: 

i was leaning to must when i wrote my initial comment, but now should sounds a lot better to me. after your input and after thinking more about it i think there might be edge cases where you can't support buffering or the use case of the console API is super specific and buffering not wanted at all (I'm thinking in the direction of something like large event stream frameworks with realtime data that you could also build with JS APIs - the JS API version of Amazon's Kinesis, like Node.js is a JS API version of a server). 

maybe that's a bit too far thought, but I'm not sure and would not feel comfortable to set the requirements so strict after these thoughts.

should sets a general expectation but does not dictate buffering for every specific implementation / use case. thanks for your input i think should would be cool.
