### ISSUE TITLE
Static console functions / binding

### ISSUE THREAD

**Issue by terinjokes** [whatwg/console#3]
Right now assigning a console function to a local variable kind of sucks, since they're expected to be called within the context of `console`. This requires the developer to bind.

```javascript
var log = console.log.bind(console);
log('＼(゜ロ＼)ココハドコ? (／ロ゜)／アタシハダアレ?');
```

Except this doesn't work in some versions of IE because the console functions aren't instances of Function!

```javascript
var log = Function.prototype.bind.call(console.log, console);
log('(ノಠ益ಠ)ノ彡┻━┻');
```

Which is a lot to type for a pretty simple and common task.

```javascript
var log = console.log;
log('＼(◎o◎)／！');
```

It makes sense to me that this is soemthing worth supporting.

**Comment by sindresorhus** [comment]
:+1: This is very convenient when you want to log the output of a callback `.catch(console.error)` or create a shortcut `const log = console.log`. This is also how it works in Node.js.

**Comment by domenic** [comment]
I don't think any browsers currently support this, although Node.js does. I think it's sensible, but I think we'd have some work to do before getting it in browsers:

- Web IDL would need to be updated with some kind of [Bound] attribute. Hmm, I wonder if [Unforgeable] would work? It wasn't meant for that purpose, but seems worth checking...
- We'd need to get at least a couple browsers to implement that.

**Comment by ak239** [comment]
FYI.
Link to chromium discussion about this: https://crbug.com/167911
And older and more informative webkit issue: https://bugs.webkit.org/show_bug.cgi?id=20141#c40

**Comment by pwnall** [comment]
I'd be happy to try to revisit WebKit and Blink implementations for bound console.log and its siblings if the standard goes in that direction. I'm still a bit annoyed when I can't pass console.log as a callback when debugging or feeling my way around new browser features, so I'd be sufficiently motivated to get it implemented.

**Comment by paulirish** [comment]
Chrome DevTools team discussed this yesterday and it's doable though more work than it appears to be. These methods are implemented in native, rather than JS. We may fix this in the next few months, though we'd be happy for your help with it @pwnall

**Comment by domenic** [comment]
@paulirish one approach that the spec might consider is to change the IDL from

```js
[NoInterfaceObject]
interface Console {
  void assert(boolean condition, optional any message);
  void clear();
  ...
};

partial interface Window {
  attribute Console console;
};
```

to

```js
// [NoInterfaceObject is gone]
interface console { // note lowercase
  static void assert(boolean condition, optional any message);
};

// no need for adding it to Window explicitly
```

This would change things slightly: `typeof window.console === "function"` would now be true, among the obvious prototype chain changes (i.e. there's no Console.prototype object). But maybe run that by your team and see what they think.

The alternative would be custom bindings of a sort.

**Comment by pwnall** [comment]
@paulirish @domenic Is this definitely going to happen in spec-land? I'm asking to make sure I don't waste effort trying to implement it. If so, I can probably find some time in the second half of February. Also, :fireworks:

**Comment by domenic** [comment]
@pwnall well, specs are driven by implementation willingness, so that question is kind of backward. If we can get at least two implementations to pledge to implement something then we can in good conscience put it in the spec.

**Comment by robertkowalski** [comment]
a typical chicken-egg situation. :)

@frewsxcv what do you think about it in regard to FF?

**Comment by frewsxcv** [comment]
For the record, I'm not in any way associated with Mozilla, other than occasional volunteer contributions for Servo. I'll link this thread to the Servo/Firefox people hoping someone more official will answer.

**Comment by jlongster** [comment]
Apparently we (Firefox) used to do this. I found this: https://bugzilla.mozilla.org/show_bug.cgi?id=989619

I can't speak for my team (devtools) but I bet most people would be fine with this. My coworker also filed this bug a while bug on a (seemingly defunct) different console repo: https://github.com/DeveloperToolsWG/console-object/issues/27

**Comment by domenic** [comment]
OK, so as discussed in https://github.com/whatwg/console/issues/1#issuecomment-181944721 and the related mailing list thread, this issue is kind of the biggest outstanding issue on this repo. And it's essentially blocked on implementer interest. Web developers really want this, as can be seen from previous discussions.

My sketch in https://github.com/whatwg/console/issues/1#issuecomment-181944721 shows how this can be done without any custom IDL bindings, which should ease the burden on implementers. But we still need at the very least explicit signals from two implementers that they are willing to do the work.

It seems like from https://github.com/whatwg/console/issues/3#issuecomment-172284926 there's some support from Chrome, on the timeline of a few months, and in https://lists.w3.org/Archives/Public/public-whatwg-archive/2016Feb/0007.html it seems like @bzbarsky voiced support if someone can volunteer to do the work in Firefox. I wouldn't say this is enough support to conclusively change the spec yet though... it would be different if someone from Firefox could commit to doing the work.

Any thoughts from Safari (@hober?) or Microsoft (@travisleithead?)?

**Comment by zcorpan** [comment]
If this is implementable with only copying webidl, it seems like it could be a "good first bug" for Firefox that @bzbarsky could mentor, maybe? Is there a bug filed?

Just changing the spec could also get the ball rolling...

**Comment by bzbarsky** [comment]
This is not a "good first bug".  It requires some tricky under-the-hood changes to the console implementation in Gecko (due to no longer having an actual Console object), and especially to its interactions with memory management and the garbage collector.  It wouldn't be so bad if console only existed on the main thread, but its existence on workers, and the ensuing need to communicate to the main-thread console, make all this very much not a "good first bug". 

So the real problem on the Gecko end is that the set of people who could quickly (a few days of work) fix this is very limited and they're all busy with other things...

**Comment by RReverser** [comment]
> due to no longer having an actual Console object

I don't know the Gecko internals, but would be it possible to make this an implementation detail for now? (like, leave Console object, but auto-bind methods when exposing)

**Comment by bzbarsky** [comment]
That would be even harder, with a smaller pool of people who can do it, actually; all that stuff is completely automated right now via the bindings generator and would require some fundamental changes to the generator to introduce that sort of hack.

Anyway, my points are: 1) this is not something we're likely to prototype quickly, and hence not likely to invest effort into unless we're pretty sure it should be done.  2)  Even once we're sure it should be done it's likely to take a few months to get to it.

**Comment by domenic** [comment]
@bzbarsky would "we're pretty sure it should be done" be influenced by changing the spec? I'd prefer to be conservative and not change without implementer support, but I recognize there's a potential chicken-egg problem here, depending on how adventurous implementers are feeling.

**Comment by bzbarsky** [comment]
> would "we're pretty sure it should be done" be influenced by changing the spec?

Probably not; it would be influenced by other implementors committing to doing it...

**Comment by foolip** [comment]
`function log() { console.log.apply(console, arguments); }` works in Edge, but which versions of IE was there a problem with console.log not being a function? Whatever the answer, this can't be remedied by updating Edge and other engines.

Is this situation substantially different from, say, `document.createElement`?

**Comment by domenic** [comment]
@foolip I think the difference is largely that developers have been asking for this for a long time, and behaviors in old-Firefox and in Node.js influenced them to expect it. The common case is `arr.map(console.log)` or similar.

**Comment by foolip** [comment]
Oh, Node.js, I skimmed past that. Going with statics would make it similar to `CSS.supports`, although having an interface called `console` would be quite unusual. WebKit seems to implement console without using IDL now, maybe it would be worth a look: http://trac.webkit.org/changeset/165199

**Comment by ak239** [comment]
ToT Chromium supports calls to console related methods without console: [crbug.com/167911](crbug.com/167911) is fixed.

**Comment by bzbarsky** [comment]
Er, with what behavior?  Is there still a `window.Console`, for example?  @domenic

**Comment by domenic** [comment]
Woah. Browsing https://codereview.chromium.org/1859293002 it looks like they've made major changes which are not at all aligned with other browsers, like moving to a data property instead of a getter/replaceable setter on the prototype. That seems quite bad.

I can't tell about `window.Console` right now.

**Comment by bzbarsky** [comment]
@domenic Can you talk to whoever is involved and figure out what the story is, please?  ;)

**Comment by ak239** [comment]
I've attached screenshot of window.console output in Chrome and Mozilla. In the both implementation we have Console object with ConsolePrototype that contains all console related methods. And it's better then was before when in Chrome we have Console with ConsoleBase prototype.
console is replaceable and each property is replaceable. I can't see the different between replaceble setter/getter and attribute. Could you figure out this?
window.Console behavior wasn't changed in Chrome it is still undefined but we can define it with constructor if necessary.
![image](https://cloud.githubusercontent.com/assets/426418/14798763/023aba82-0aee-11e6-9013-972a3f6b72db.png)

**Comment by bzbarsky** [comment]
> and each property is replaceable.

Replaceable in what sense?  In Gecko you can set `console.log = whatever` and this will shadow the prototype property, obviously, but `Console.prototype.log` will still be the original thing, of course.  If you're putting props on a prototype in Chrome, that should give the same behavior, obviously.

There shouldn't be any getters/setters here, because Console has no attributes, only methods ("operations" in IDL-speak).

**Comment by domenic** [comment]
There's the question of what Object.getOwnPropertyDescriptor(window, "console") returns. That is what is changed by the Chrome patch to be incompatible with other browsers.

**Comment by bzbarsky** [comment]
Ah, ok.  _That_ getter!

**Comment by domenic** [comment]
It looks like Chrome's new version (which is testable in Canary) still uses prototypes, not own properties. So e.g.

```js
console.__proto__.log(5)
```

works. That is, `ConsolePrototype` is just an object with a bunch of functions, none of which depend on `this`.

This is certainly not how I would have done this. I see a few reasonable options that I think could be achieved across browsers:

- (The status quo) use Web IDL semantics, where `window.console` is an instance of `Console` and its methods cannot be extracted and used without an instance.
  - `console.prototype` does not exist
  - `console.__proto__` is a `ConsolePrototype` with lots of non-extractable methods
- ([The hack](https://github.com/whatwg/console/issues/3#issuecomment-172285367)) use Web IDL "static" semantics, where `window.console` is a "class" with a throwing constructor and a bunch of static methods.
  - `console.prototype` exists and is an empty object
  - `console.__proto__` is `Function.prototype`.
- (The JSey way) `window.console` is a plain object with a bunch of function properties, similar to `window.Math`.
  - `console.prototype` does not exist
  - `console.__proto__` is `Object.prototype`.

Instead Chrome seems to implement something completely different:

- (The new Chrome) `window.console` is an instance of the Console class, whose prototype has a bunch of extractable functions
  - `console.prototype` does not exist
  - `console.__proto__` is a `ConsolePrototype` with lots of non-method functions.

**Comment by ak239** [comment]
Current approach can be easily transformed into second or third one.

**Comment by domenic** [comment]
OK. I assume other browsers would prefer something implementable in Web IDL, so "the hack" instead of "the JSey way"?

**Comment by paulirish** [comment]
The CL we put up on Friday was intending to fix the issue detailed at the top here. We originally wanted to match Mozilla's implementation, but yeah acknowledge there is some difference.

----

Moving forward, we definitely prefer "the JSey Way". The goal of this improvement is to make the console more accessible to JavaScript, so we'd prefer a plain old object that's easy to reason about rather than a class that's cannot be instantiated.

**Comment by ak239** [comment]
I've uploaded CL to align our solution with (The JSey way): [https://codereview.chromium.org/1921143002/](https://codereview.chromium.org/1921143002/)

**Comment by domenic** [comment]
OK. I prefer "the JSey way" as well, but would like to hear from some other implementers (like @bzbarsky) whether they think that's feasible... Maybe @DigiTec has opinions as well? We're talking about changing `console` to a plain JS object with functions that can be extracted and called with `undefined` this value, instead of an instance of a `Console` class with a prototype specified using Web IDL.

**Comment by DigiTec** [comment]
We aspire to have everything come through WebIDL. Which puts huge stress on features like window.chrome since it is a raw JS object. Our engine prefers things that have types and prototypes and are otherwise extensible by the JS developer. Having a mix of prototype based objects and other objects that aren't prototype based means JS developers have to think hard about how to extend and use different types.

Are we trying to work around a WebIDL limitation? Not every function has to be this validating. toString doesn't validate the "this" pointer in some cases. Do we want something akin to `[LenientThis]` for functions that we'd like to use without the instance? Basically remove the instanceof check? 

I'm of the opinion that we have nearly 600 defined types now and Console shouldn't be a special case if we can avoid it. If we need a semantic then it should be a supported semantic available to new types in the type system and we should have some idea of who might use said types.

**Comment by bzbarsky** [comment]
> We originally wanted to match Mozilla's implementation

Except you matched the implementation Mozilla had a long time ago, not the one Mozilla has had for the last two years, yes?

For the rest, if we do this as a plain object ... it's moderately annoying in terms of needing special-casing, but probably not actually fatal in this particular case because the IDL for Console seems to consist only of things without much interesting argument processing.  Most of the methods take `any...` and then do manual handling anyway.  A few take no arguments.  `assert` takes a boolean, which is pretty simple to do by hand.  Having to hand-roll the code to define the property on the global and the various member functions on that object is rather annoying, as I said, but survivable.

Of course in practice we may end up doing the "idl hack" and just add some extended attributes to create a non-function interface object or something.  The only relevant observables there are typeof, console.__proto__, and console.prototype, and this last would already be undefined in Gecko for an abstract thing with only static stuff on it, so we'd just need to deal with the first two.  I believe the end result would not be black-box distinguishable from the jsey thing... except for what `window.console.toString()` returns.  What _should_ it return?  Note that `Math.toString()` returns something that's not `"[object Object]"`.

**Comment by domenic** [comment]
> For the rest, if we do this as a plain object ... it's moderately annoying in terms of needing special-casing, but probably not actually fatal in this particular case because the IDL for Console seems to consist only of things without much interesting argument processing. 

See also #26. A few things in the current spec take something more complicated than `any...` (mainly `DOMString` or variants) but preliminary implementation testing reveals that `any` or `any...` might be more appropriate.

> Of course in practice we may end up doing the "idl hack" and just add some extended attributes to create a non-function interface object or something.

It sounds like this would be strongly preferred by @DigiTec as well. I agree the easiest trick would be to add something like [Namespace] to IDL so that

```webidl
[Namespace]
interface console {
  static void error(any... data);
  // ...
}
```

generates a singleton with `typeof console === "object"`, `console.prototype === undefined`, and `console.__proto___ === Object.prototype`. We'd presumably define that `[Namespace]` interfaces can only have static members.

Or we could try to do something prettier and make the syntax

```webidl
namespace console {
  void error(any... data);
  // ...
}
```

but I imagine adding an extended attribute is easier than adding a new keyword, as it doesn't require parser changes. If any implementers want to confirm or deny my suspicions there that would be appreciated.

> except for what window.console.toString() returns. What should it return?

I don't think this matters very much, but in https://github.com/tc39/ecma262/issues/495 it was explained that the intention for "new" namespace objects like Reflect is to not have them gain a toStringTag; Math is "legacy" in that sense. But console is very old so I don't really care about whether it gets a toStringTag or not.

**Comment by bzbarsky** [comment]
Ah, namespace is a good way to put it.  There's been talk in the past of adding something like that, and even nested namespaces.  e.g. CSS could use that setup (and in Gecko, `CSS.prototype` is undefined).  Of course some things started out as namespaces and then became classes (see `URL`).

**Comment by JosephPecoraro** [comment]
I agree that a namespace object would be much better. We landed this in WebKit today. [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=157286), [WebKit r200350](http://trac.webkit.org/changeset/200350).

We kept `console.toString()` outputting `"[object Console]"`, since it seems it would qualify as "legacy" given how long it has been around. However, I don't foresee any problems with it moving to `"[object Object]"`.

**Comment by domenic** [comment]
Oh wow, that is really great to hear!

It seems like at this point neither Blink nor WebKit is using IDL for their console object. But, Gecko and Edge would both prefer to keep things in IDL. Which is fine; we can just use IDL to describe things and people can implement them any which way as long as the semantics are the same.

@bzbarsky, @DigiTec, do you have any preference between the two forms of "new" IDL in https://github.com/whatwg/console/issues/3#issuecomment-214586757 ? As I said, I think `namespace console` is nicer for people reading the IDL, but `[Namespace] interface console` + static members might be easier to parse/integrate/etc. Would love to hear your thoughts so we can put this into the spec.

**Comment by bzbarsky** [comment]
I don't have a strong preference.  Even if the spec says `namespace` nothing stops us from using `[Namespace] interface` in our source tree if that's simpler in the short term.

The hard part of this for us will be the semantic changes and the actual behavior change (because we store actual state on the Console object that's the `this` value), not the IDL parsing.

**Comment by domenic** [comment]
That's a good point. OK, cool. I will work on a pull request to IDL to add `namespace`.

In the meantime, maybe it would be good to add a warning to the spec along the lines of "The above IDL is not accurately aligned with recent implementation progress, which makes `console` a "namespace object" instead of an interface. See https://github.com/whatwg/console/issues/3 for details. We will be updating the specification as soon as IDL has proper support for such namespace objects."

**Comment by bzbarsky** [comment]
For what it's worth, I have work in progress to support something like `namespace console` in https://bugzilla.mozilla.org/show_bug.cgi?id=1270601

I added an extended attribute to do the `"[object Console]"` thing too, but that could presumably be defined directly in terms of a static symbol-named attribute if we want it; we just need IDL syntax for symbol-named attributes.

**Comment by bzbarsky** [comment]
I do think, by the way, that we want to support `[Exposed]` on namespaces.  And we should consider changing `CSS` to be a namespace...

**Comment by domenic** [comment]
I feel like we should either declare that all namespaces have `[object NamespaceName]` or none of them. So either it should automatically be a feature of namespaces or console should become `[object Object]`.

**Comment by bzbarsky** [comment]
`[object NamespaceName]` would not do the right thing in this case because the namespace is `console`.  Unless you mean that the namespace name should be taken and then initial-capped.

It might well be possible to move to `[object Object]` in general.  But I don't want to hold the main change hostage to that, so like the WebKit folks will preserve the stringification for now; then as a separate change we can look into changing it if people feel that we should.

**Comment by domenic** [comment]
The namespace name would be console. [Replaceable] readonly attribute Console console, as now. (You could theoretically expose the same namespace object via multiple properties, e.g. attribute Console console2.)

**Comment by bzbarsky** [comment]
Oh, hmm.That's ... not at all what I was expecting the namespace thing to act as.  I was expecting more that "namespace console" means there is a property on the global named "console" (just like "interface console" would do), but that the "namespace" bit means it's not a function object or any of that jazz.  That's what was described above.

Your proposal of defining "namespace" as a type that can be returned from random places, is introducing a bunch of complexity that I don't think we need here....

**Comment by bzbarsky** [comment]
(And a bunch of specification complexity; for example, what actually ensures that two different getters return the same object in terms of object identity?)

**Comment by domenic** [comment]
I see, in your proposal namespace objects can only be exposed on the global, and automatically get exposed by being declared. Seems reasonable.

**Comment by domenic** [comment]
I've put out a PR for namespaces in Web IDL: https://github.com/heycam/webidl/pull/121

**Comment by JosephPecoraro** [comment]
WebKit has seen a compatibility issue due to moving to namespaces. It also appears in Chrome Canary. On [macupdate](http://www.macupdate.com/app/mac/25347/phoneview), global code attempts to modify `console.__proto__.debug`:

```javascript
console.__proto__.debug = function(format) {
    if (window.DEBUG) {
        var varargs = Array.prototype.slice.call(arguments);
        console.__proto__.info.apply(this, varargs)
    }
}
```

Unfortunately this puts a global, enumerable, property on Object.prototype, so later code that iterates properties of an object via for..in unexpectedly gets the property "debug".

```javascript
for (var propertyName in {})
    console.log(propertyName);
// [Log] debug
```

Maybe there are more users of `console.__proto__`?

WebKit hasn't made any decision yet on what to do, but I thought I'd mention it.

**Comment by bzbarsky** [comment]
@domenic Would be good to have this sorted out so Firefox can ship this change, but in a web-compatible way....

**Comment by domenic** [comment]
This seems like something we'd need implementers to decide on.

Per that bug, WebKit has gone with adding an empty object named `__proto__` to console. (If I were to spec that, I'd probably add an extended attribute `[LegacyDummyProto] for use on namespaces, which hopefully only `console` would ever use; with luck CSS could get away without it.)

But how does Gecko feel about the potential compatibility hit? How does Chrome? (@paulirish @ak239) Edge? (@andysterland) If most browsers are interested in pushing through without such a hack, we probably shouldn't spec it, but I don't really know yet.

**Comment by domenic** [comment]
Oh, and there's two potential hacks here:

(A) Make console's [[Prototype]] a new empty object
(B) Add an own property named `"__proto__"` whose value is an empty object.

(The difference is observable because for (A), `Object.getPrototypeOf(console)` will return the empty object; for (B) it will return `Object.prototype`.)

WebKit seems to have gone with (A). I was originally thinking that (B) would be better, but upon reflection it's probably too weird and could potentially cause compatibility issues.

Note that neither (A) nor (B) really fixes the original demo code shown by @JosephPecoraro:

```js
console.__proto__.debug = function(format) {
    if (window.DEBUG) {
        var varargs = Array.prototype.slice.call(arguments);
        console.__proto__.info.apply(this, varargs)
    }
}
```

I believe that this will still fail, once it reaches the line `console.__proto__.info.apply(this, varargs)`. Maybe that line is reached more rarely than the `for-in` he talked about, though.

**Comment by JosephPecoraro** [comment]
>  I believe that this will still fail, once it reaches the line `console.__proto__.info.apply(this, varargs)`

We were aware of the possible issue, but were fine with the trade offs.

You are correct that the `apply` would fail, but in practice it is unlikely to be reached. This particular page doesn't seem to call `console.debug` anywhere or make use of its new function by any other name. However, were the page were to do `console.debug("foo")` (which we considered the most likely use) it would use the unaffected native `console.debug` on the namespace object and not the fragile `console.__proto__.debug` the page defined.

**Comment by zcorpan** [comment]
@domenic if the hack is a one-off, it can be prose in the console spec rather than new extended attribute in Web IDL.

**Comment by zcorpan** [comment]
I did a quick search in httparchive (494k pages), only 3 resources that do `__proto__` or `getPrototypeOf` on `console` or `CSS`.

```
SELECT COUNT(*) AS num, REGEXP_EXTRACT(body, r'(\b(?:(?:CSS|console)\.__proto__|getPrototypeOf\(\s*(?:[a-zA-Z]+\.)*(?:CSS|console)\s*\)).*)') as match
FROM [httparchive:har.2016_04_15_chrome_requests_bodies]
GROUP BY match
ORDER BY num DESC
```
Row | num | match 
---|---|---|---
1 | 17616995 | null 
2 | 1 | `console.__proto__.debug=function(format){if(window.DEBUG){var varargs=Array.prototype.slice.call(arguments);console.__proto__.info.apply(this,varargs)}},_mu.utils.renderTemplate=function(elementId,data,namespace){if("string"!=typeof elementId||elementId.length<=0)return console.error("No element ID specified"),!1;namespace=namespace||"data";var templateElement=document.getElementById(elementId);if(null===templateElement||void 0===templateElement)return console.error("Unable to find template with ID '"+elementId+"'"),!1;var html=document.getElementById(elementId).innerHTML;return _.template(html,{variable:namespace})(data)},_mu.utils.AJAXJSONRequest=function(route,action,payload,callback){var url="/"+route+"/"+action+"/format/json",params=new FormData;"object"==typeof payload&&Object.keys(payload).length>0&&Object.keys(payload).map(function(key){params.append(key,payload[key])});var xhr=new XMLHttpRequest;xhr.open("POST",url,!0),xhr.onreadystatechange=function(){if(4===xhr.readyState&&"function"==typeof callback){var response=xhr.responseText;try{response=JSON.parse(xhr.responseText)}catch(ex){console.error("%s",ex),response={}}callback(response)}},xhr.send(params)},_mu.utils.forceRepaint=function(selector){if(null===selector||void 0===selector||selector.length<1)return!1;var element=document.querySelector(selector);return null!==element?(element.style.display="none",element.offsetHeight,element.style.display="",!0):!1},_mu.utils.serializeForm=function(form){if(!(form instanceof HTMLFormElement))return!1;for(var elements=form.elements,data={},i=0;i<elements.length;i++){var element=elements[i],key=element.getAttribute("name"),value=void 0;if(key&&element.type){switch(element.type.trim().toLowerCase()){case"text":case"textarea":default:value=element.value;break;case"radio":case"checkbox":value=value.checked}data[key]=value}}return data},_mu.utils.animateElement=function(element,animation,duration,startCallback,endCallback){if(!(element instanceof HTMLElement))return console.error("Parameter `element` must be an instance of `HTMLElement`"),!1;if("string"!=typeof animation||animation.length<1)return console.error("No animation specified"),!1;var specifiedDuration=!("string"!=typeof duration||-1===_mu.utils.animateElement.durations.indexOf(duration)||"normal"===duration),startCallbackProxy=function(event){"function"==typeof startCallback&&startCallback(event),element.removeEventListener("animationstart",startCallbackProxy)},endCallbackProxy=function(event){"function"==typeof endCallback&&endCallback(event),element.classList.remove("animated",animation,duration),element.removeEventListener("animationend",endCallbackProxy)};element.addEventListener("animationstart",startCallbackProxy),element.addEventListener("animationend",endCallbackProxy),specifiedDuration?element.classList.add("animated",duration,animation):element.classList.add("animated",animation)},_mu.utils.animateElement.animations=["slideInDown","slideInLeft","slideInRight","slideInUp","slideOutDown","slideOutLeft","slideOutRight","slideOutUp","fadeIn","fadeInDown","fadeInDownSmall","fadeInLeft","fadeInRight","fadeInUp","fadeOut","fadeOutDown","fadeOutLeft","fadeOutRight","fadeOutUp","fadeOutUpSmall","slideInFadeInDown","slideOutFadeOutUp","slideInFadeInUp","slideOutFadeOutDown","modalDialogOpen","modalDialogClose"],_mu.utils.animateElement.durations=["slow","normal","fast"];`
3 | 1 | `console.__proto__;_.each(_.keys(functions),function(key){if(typeof functions[key]=="function"){this[key]=function(){if(self.logging){console[key].apply(console,arguments)}};self.enabled[key]=true}},this)}else{window.console=this}_.each(consoleInterface,function(functionName){if(this[functionName]===undefined){this[functionName]=function(){};self.enabled[functionName]=false}},this)}})(window,window.jQuery,window._,window.console,window.SiteTools.Core);Namespace("SiteTools.Core");(function(window,$,_,console,core){window.SiteTools.Core.Event=new function(){var self=this;this.logging=true;this.log=function(groupTitle,groupArgs){if(this.logging){if(core.Console.enabled.groupCollapsed){console.groupCollapsed(groupTitle);if(core.Console.enabled.dir){console.dir(groupArgs)}else{console.log(groupArgs)}console.groupEnd()}else{console.log(groupTitle)}}};this.Bindings=[];this.Trigger=function(event,args){self.log(String.Format("Event '{0}' triggered",event),{"Arguments":args});var curBindings=_.filter(this.Bindings,function(binding){return binding.event==event});_.every(this.Bindings,function(binding){if(binding.context.nodeName&&binding.context!==window.document){if(!$(binding.context).closest("html").length){self.Unbind(binding.event,binding.eventHandler,binding.context)}}});_.every(curBindings,function(binding){var eventArgs={type:event,data:args,cancelBubble:false};binding.eventHandler.call({},eventArgs);if(eventArgs.cancelBubble===true){self.log(String.Format("Event bubble canceled for event '{0}'",event),{"Arguments":eventArgs});return false}else{return true}});if(event!="EventTrigger"){this.Trigger("EventTrigger",{type:event,data:args})}};this.Bind=function(event,eventHandler,context){context=context||window.document;if(!this.HasEventHandler(event,eventHandler,context)){if(context instanceof $){context.on("remove",function(e){self.Unbind(event,eventHandler,context)});context=context[0]}this.Bindings.unshift({event:event,eventHandler:eventHandler,context:context});self.log(String.Format("Event '{0}' bound",event),{"Event Handler":eventHandler.toString()})}};this.Unbind=function(event,eventHandler,context){context=context||window.document;if(context instanceof $){context=context[0]}var binding,bindings;if(!eventHandler){bindings=_.where(self.Bindings,{event:event,context:context});_.each(bindings,function(b){self.Bindings.splice(_.indexOf(self.Bindings,b),1)})}else{binding=_.find(this.Bindings,function(b){return(b.event===event&&b.eventHandler.toString()===eventHandler.toString()&&context===b.context)});this.Bindings.splice(_.indexOf(this.Bindings,binding),1)}};this.HasEventHandler=function(event,eventHandler,context){return typeof _.find(this.Bindings,function(b){return(b.event===event&&b.eventHandler.toString()===eventHandler.toString()&&context===b.context)})!=="undefined"};return self};$(function(){core.Event.Bind("Load",function(event){var context=typeof event.data==="undefined"?"html":event.data;$("*[data-triggerevent]",context).safebind("click",function(){var triggerevents=$(this).data("triggerevent");_.each(triggerevents.split(","),function(triggerevent){core.Event.Trigger(triggerevent)})})});core.Event.Trigger("PagePreLoad");core.Event.Trigger("PageLoad");core.Event.Trigger("PagePostLoad")})})(window,window.jQuery,window._,window.console,window.SiteTools.Core);`
4 | 1 | `console.__proto__;_.each(_.keys(functions),function(key){if(typeof functions[key]=="function"){this[key]=function(){if(self.logging){console[key].apply(console,arguments)}};self.enabled[key]=true}},this)}else{window.console=this}_.each(consoleInterface,function(functionName){if(this[functionName]===undefined){this[functionName]=function(){};self.enabled[functionName]=false}},this)}})(window,window.jQuery,window._,window.console,window.SiteTools.Core);Namespace("SiteTools.Core");(function(window,$,_,console,core){window.SiteTools.Core.Event=new function(){var self=this;this.logging=true;this.log=function(groupTitle,groupArgs){if(this.logging){if(core.Console.enabled.groupCollapsed){console.groupCollapsed(groupTitle);if(core.Console.enabled.dir){console.dir(groupArgs)}else{console.log(groupArgs)}console.groupEnd()}else{console.log(groupTitle)}}};this.Bindings=[];this.Trigger=function(event,args){self.log(String.Format("Event '{0}' triggered",event),{Arguments:args});var curBindings=_.filter(this.Bindings,function(binding){return binding.event==event});_.every(this.Bindings,function(binding){if(binding.context.nodeName&&binding.context!==window.document){if(!$(binding.context).closest("html").length){self.Unbind(binding.event,binding.eventHandler,binding.context)}}});_.every(curBindings,function(binding){var eventArgs={type:event,data:args,cancelBubble:false};binding.eventHandler.call({},eventArgs);if(eventArgs.cancelBubble===true){self.log(String.Format("Event bubble canceled for event '{0}'",event),{Arguments:eventArgs});return false}else{return true}});if(event!="EventTrigger"){this.Trigger("EventTrigger",{type:event,data:args})}};this.Bind=function(event,eventHandler,context){context=context||window.document;if(!this.HasEventHandler(event,eventHandler,context)){if(context instanceof $){context.on("remove",function(e){self.Unbind(event,eventHandler,context)});context=context[0]}this.Bindings.unshift({event:event,eventHandler:eventHandler,context:context});self.log(String.Format("Event '{0}' bound",event),{"Event Handler":eventHandler.toString()})}};this.Unbind=function(event,eventHandler,context){context=context||window.document;if(context instanceof $){context=context[0]}var binding,bindings;if(!eventHandler){bindings=_.where(self.Bindings,{event:event,context:context});_.each(bindings,function(b){self.Bindings.splice(_.indexOf(self.Bindings,b),1)})}else{binding=_.find(this.Bindings,function(b){return(b.event===event&&b.eventHandler.toString()===eventHandler.toString()&&context===b.context)});this.Bindings.splice(_.indexOf(this.Bindings,binding),1)}};this.HasEventHandler=function(event,eventHandler,context){return typeof _.find(this.Bindings,function(b){return(b.event===event&&b.eventHandler.toString()===eventHandler.toString()&&context===b.context)})!=="undefined"};return self};$(function(){core.Event.Bind("Load",function(event){var context=typeof event.data==="undefined"?"html":event.data;$("*[data-triggerevent]",context).safebind("click",function(){var triggerevents=$(this).data("triggerevent");_.each(triggerevents.split(","),function(triggerevent){core.Event.Trigger(triggerevent)})})});core.Event.Trigger("PagePreLoad");core.Event.Trigger("PageLoad");core.Event.Trigger("PagePostLoad")})})(window,window.jQuery,window._,window.console,window.SiteTools.Core);/* Built on BSWE-SI-BUILD02 at 3/17/2016 10:24:25 AM */`

**Comment by ak239** [comment]
In Chrome we'd like to fix problem with console.__proto__ as soon as possible and are going to land (A) as temporary solution.
I think that we can add a warning message when someone set something on console.__proto__ .

**Comment by danzen** [comment]
Hi folks, over the last couple of versions of Firefox, the binding of console.log is no longer giving the file and line numbers in very right hand column of the console.  It now says (unknown).  Other browsers still work.  Is there a way for me to solve this as it is important for my public library http://zimjs.com.  I am using: 

`var log = console.log.bind(console);`

also tried with no success:

`var log = Function.prototype.bind.call(console.log, console);`

Thank you!

**Comment by domenic** [comment]
@danzen that seems unrelated to this issue; I'd suggest filing a bug on the Firefox issue tracker, not commenting on an issue on the console standard.

**Comment by danzen** [comment]
@domenic thanks - I think I did that a few weeks ago - I will check on that... sorry did not realize that this was for standards.  Cheers for all your work.

**Comment by domenic** [comment]
Thanks everyone for your help along this long journey! The spec is now updated, including the special prototype object.

- Web platform tests are up at https://github.com/w3c/web-platform-tests/pull/3994
- Edge bug filed at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9392959/
- Chrome bug tracker currently inaccessible, but here is a non-canonical URL of the bug for Chrome's enumerability: https://monorail-prod.appspot.com/p/chromium/issues/detail?id=656826
