### ISSUE TITLE
console.trace specification

### ISSUE THREAD

**Issue by timoxley** [whatwg/console#35]
[Current specification](https://console.spec.whatwg.org/#trace-data) for `console.trace` seems either incomplete or at odds with the current "print a stack trace" behaviour in most console implementations.

![image](https://cloud.githubusercontent.com/assets/43438/12450466/de6c5efa-bfbe-11e5-8d7e-7158ca2e7a14.png)

What, if any, are the plans on standardisation of `console.trace`?

Possibly related to https://github.com/whatwg/javascript/issues/26

**Comment by robertkowalski** [comment]
Hi @timoxley! Thanks for reporting!

Looks like you've found a bug / incomplete section. We just started and will improve the spec. Some sections are still incomplete or have some rough edges. 

Right now I can't promise anything regarding my schedule.

**Comment by domenic** [comment]
@timoxley would you be willing to submit a PR? I think it's OK to be vague since there's no stack trace spec, but just describing roughly what implementations do would be super useful.

**Comment by domfarolino** [comment]
I wouldn't mind taking a stab at it if that's alright. One question though, I was looking into what exactly `console.trace()` would print when calling from a bound function, i.e:

```js
function foo() {
  console.trace();
}

const obj = {a: 10};

const objFoo = foo.bind(obj);
objFoo(); // traces "foo" not "bound foo", though objFoo's .name prop = "bound foo"
```

Personally I thought this was kind of odd (& possibly not as useful as it could be), and I actually found the following text in the ["You Don't Know JavaScript"](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch2.md) book and didn't know if this was expected behavior or not.

<img width="905" alt="screen shot 2016-11-14 at 12 18 16 am" src="https://cloud.githubusercontent.com/assets/9669289/20254224/5c38fa6a-aa00-11e6-82a1-2b2a9b089777.png">

It seems there is no spec around this yet (and I cannot reproduce what the book says in a browser), so I can include some text about the current behavior in a PR, but wasn't sure if that would be outside of the scope of what we should explain. Thoughts?

**Comment by robertkowalski** [comment]
Hi @domfarolino,

thats a good question! So the spec says in http://www.ecma-international.org/ecma-262/6.0/#sec-function.prototype.bind

```
15 Perform SetFunctionName(F, targetName, "bound").
```

After working a bit with bindings and functions and logging I came to this conclusion: the binding of a function is not relevant right now for logging (as you noticed in the output of console.trace). 

If we would want to change that, we have to find implementors support.

I see that it could be helpful to have it. For now, we can start to write the missing parts for this issue and adjust as soon as we get implementors support. Does that make sense?

**Comment by domfarolino** [comment]
@robertkowalski Ok, I can write a simple description of how console.trace() behaves currently etc but just to make sure we're on the same page, we are saying there doesn't need to be text (yet) about the fact that the original function name is used in a trace and not some modified name indicating it was bound correct?

Regardless, if there's anything else I should be aware of just let me know - first time contributing to a spec haha.

**Comment by domenic** [comment]
Yeah, I think the exact details of how to assemble a stack trace (e.g. what function names to use) are OK to leave vague, because really that's the JavaScript spec's job to specify, and it hasn't picked up that task itself yet.

I wonder if `console.trace()` uses the same function names or stack trace formatting as `(new Error()).stack`? If so it might be worth mentioning that inside a `<p class="note">`.

**Comment by JosephPecoraro** [comment]
>  if there's anything else I should be aware of just let me know

This probably is not well known, but some debuggers will prefer showing a Function's `displayName` property value over its `name` property. This tends to happen in profilers, but checking around it also happens in `console.trace`. While this used to be a much bigger problem before ES6 added inferring function names, it can still be useful to name a function something that would be impossible otherwise.

While there are no official docs, there are some old and recent references. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName) says:

> It is usually preferred by consoles and profilers over func.name to display the name of a function.

You can find [other](https://medium.com/@cramforce/on-the-awesomeness-of-fn-displayname-9511933a714a#.rmlrcuaih) [examples](http://www.alertdebugging.com/2009/04/29/building-a-better-javascript-profiler-with-webkit/) with minimal web searching (dating back to ~2009).

Example:

```html
<script>
function foo() { bar(); }
function bar() { console.trace(); }
foo.displayName = "foo display name";
foo();
</script>
```

Displays like this in Safari:

```
[Log] Trace
	bar (example.html:4)
	foo display name (example.html:2)
	Global Code (example.html:5)
```

Note Safari uses its own localized strings for things like "Global Code", "Eval Code", and more. I'm not sure how much of this needs to or should be specified, but I thought I'd bring it up.
