### ISSUE TITLE
steps language on the Logger method

### ISSUE THREAD

**Issue by leobalter** [whatwg/console#49]
The current steps for Logger seemed confusing. I highlighted some parts:
1. Let first be the first element of args. **If** args is empty, **abort these steps**.
2. Let rest be all elements following first in args.
3. If rest is empty, **print** first to the console. **Abort these steps**.
4. If first does not contain any format specifiers, perform Printer(logLevel, args).
5. Otherwise, perform Printer(logLevel, Formatter(args)).
6. Return undefined.
- step 1: "abort these steps": which steps?
- step 1: "If args...": is it possible to split it to a next step?
- step 3: "print first to the console": use `perform Printer(logLevel, first)` instead?
- step 3: "Abort these steps": which steps?
- maybe "perform Printer" steps can be replaced by `return Printer` and let `Printer` return undefined. This will follow some consistency with other methods as `Formatter(args)`. 
- other functions are calling `Perform Logger`, they could also be replaced by `Return Logger`.

**Comment by domenic** [comment]
In general "abort these steps" is a common idiom which means to abort the set of steps you are currently in. (I.e. the steps you refer to as step 1, 2, 3, ...). So I am not concerned about that.

Step 1 could indeed be split into two steps if you want.

Good catch that step 3 should use Printer instead.

I don't think changing perform to return helps anything; it just makes it harder to track as you have to then go find out that Printer doesn't return anything.

So yeah, a pull request from anyone would be welcome to:

- Split step 1 into two steps, first checking if args is empty and aborting if so, and second getting the first element
- Use Printer in step 3, instead of "print first ot the console".

**Comment by leobalter** [comment]
thank you! @terinjokes and @domenic!
