### ISSUE TITLE
console.time with no arguments

### ISSUE THREAD

**Issue by JosephPecoraro** [whatwg/console#54]
What should be the behavior of `console.time` with no arguments?

Currently the spec shows a single non-optional argument:

```
interface Console {
  void time(DOMString label);
  void timeEnd(DOMString label);
};
```

Current behavior of `console.time()` and `console.timeEnd()`:
* Firefox - silently does nothing
* Chrome - silently does nothing
* node.js - starts/stops an unnamed timer
* Safari - throws an exception, warning the user they need to provide a label
* Edge - starts/stops a timer named `"default"`, console.warns when called and the timer is/not running

Current behavior of `console.time("name")` and `console.timeEnd("name")`:
* All environments behave the same

I have to admit I rather like both node and Edge's behavior here. WebKit's is nice in that it indicates a likely user error that would otherwise cause a developer to scratch their head, but an exception is overkill. node and Edge make it simple to do a quick and dirty time & timeEnd, which is what developers will want most of the time.

I would suggest a move in the Edge direction.

Proposed:

```
interface Console {
  void time(optional DOMString label = "default");
  void timeEnd(optional DOMString label = "default");
};
```

Playing around with Edge's implementation, it seems that any falsey value (e.g. `false`, `0`, `NaN`, `""`, ...) is coerced to the string `"default"`. I don't know of an IDL attribute for this kind of behavior (`[TreatFalseyAs="default"]`), or if it would be desirable to spec this quirk. However, it does seem very user friendly.

Comparing node and Edge, node is rather ambiguous. node seems to treat `label` as a value and ambiguously displays string names for values that aren't treated as strings internally. For instance `console.time(123)` and `console.time('123')` are treated uniquely, but based on warning messages from node they are not distinguishable. Likewise `undefined` versus `"undefined"`. I could see this being extended to with object / Symbol values.

Ultimately I don't think non-string values as identifiers are necessary for `console.time()`. And given all browsers currently expect strings, it seems easier to stick with that expectation.

_Update: Added node.js to the discussion._

**Comment by JosephPecoraro** [comment]
More information about Edge from documentation:
[Docs showing optional WebIDL](https://msdn.microsoft.com/en-us/library/dn265071.aspx)
[Docs describing timers](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/f12-devtools-guide/console/using-the-console-api/#timers)

Interestingly the documentation says:

> If you don't pass an argument, the methods use "default" as the label.

However their implementation doesn't quite match that from the other falsey cases.

**Comment by domenic** [comment]
Per @DigiTec in https://github.com/whatwg/console/issues/3#issuecomment-214571019, I think we should try to stick with semantics that are expressible in Web IDL. So your proposal makes sense, even if it doesn't match what Edge currently does exactly. Hopefully Edge would be willing to align?

/cc @ak239 @paulirish from Blink and @bgrins from Gecko to see if they're OK with aligning on `optional DOMString label = "default"` for time()/timeEnd(). For non-IDL implementations, this would look like

```js
console.timeEnd = (label = "") => {
  label = %IntrinsicToString(label);
  // ...
};
```

There's also the question of what browsers do with input like `{ toString() { throw new Error("boo!"); } }`. Per this proposal they should rethrow the error, but I'm not sure all of them do so far.

**Comment by bgrins** [comment]
Agreed about aligning on `optional DOMString label = "default"` - this behavior seems more useful than a silent failure when calling with no args.

> There's also the question of what browsers do with input like { toString() { throw new Error("boo!"); } }. Per this proposal they should rethrow the error, but I'm not sure all of them do so far.

We should keep the current WebIDL semantic and rethrow the error in this case.

**Comment by DigiTec** [comment]
For Edge, I'm not in control of this feature. This is a no-op when the F12 tools are not attached and they inject their own implementation when the tools are attached. So I, unfortunately, cannot do more here than influence them by forwarding this issue along.

**Comment by domenic** [comment]
Having web-exposed behavior, like throwing, change depending on whether devtools are open seems quite bad. If that's a requirement for some vendors, we should change it to `optional any label = "default"` and do nothing if the value is not a string.

Do any other vendors prefer to do something similar?

**Comment by andysterland** [comment]
[Quick intro: I'm the PM for the developer tools in Edge.]

For what it's worth at least from Edge/IE we prefer to never throw or return any value back to the caller for console.*. The idea being that the console is an output only channel and shouldn't impact the state of the page. 

If I recall for console.time our behavior is:
1. If the argument is `undefined` or the value is `falsey` label the timer `default` 
2. Else if string use that or if not a string then the result of `.toString()`
This does cause some weirdness as the value `false` will get you a label of `"default"` but `true` would get you a label of "`true`".

**Comment by domenic** [comment]
@andysterland thanks for dropping by. I can understand the idea of not wanting to ever throw exceptions.

A couple questions:

- Is it important to you that we define the behavior of `console` using Web IDL? In https://github.com/whatwg/console/issues/3#issuecomment-214571019 @DigiTec expressed a preference for this, but Blink and WebKit do not use Web IDL here, so we are unsure whether that is important.

- "Else if string use that or if not a string then the result of .toString()" implies you are OK throwing if the value is `{ toString() { throw new Error("boo"); } }`. Would you prefer to throw in that case, or ignore the value (act as if `time()` was never called)?

- The falsey behavior is unlike most things on the web platform. Would you be willing to change things so that only `undefined` triggers the default, instead of any falsey value?

**Comment by andysterland** [comment]
1. In general, yes. Though perhaps Edge/IE is unique and the Web IDL is used to define what happens when the tools aren't open. But, when the tools are open we inject a bunch of code that does the logging etc. Our console code doesn't make use of Web IDL (it's all TypeScript). The approach we've taken so far has been that the signatures should all be defined in Web IDL but what happens in the tools when the user calls `console.*` isn't defined in Web IDL or indeed in code at all. The goal being that we wanted flexibility to do what we felt was best for the developer experience. In practice the biggest diversion here has been around optional arguments that don't semantically impact anything but can offer some affordances in the tools UI for example if you did `console.group(DOMString header)` a tool might want to have a header displayed etc. I don't think on the tools side we are as wed to following the semantics of Web IDL especially if it's going to lead to worse experiences. In particular I think the biggest sticky point there will be around throwing exceptions and even testing for the existence of APIs (I believe FF for a while even had it so that invoking `console.*` that weren't implemented didn't throw - but perhaps that was removed?). The purpose of the console is very different from the rest of the DOM. Hell it be great if production code never, ever, had a call to a `console.*` API which you can't really say about the rest of the DOM.
2. If the implementation of `toString` contains an exception we catch it and don't start the timer. We don't even log the exception to the console. We decided not to warn for it as it felt like an edge case. 
3. Sure our logic today is super naïve and this behavior is more of a result of that than a design.

**Comment by domenic** [comment]
OK, great. It sounds to me like the best behavior would be to change the signature to `optional any label = "default"`, and have the first line of the algorithm be: if `label` is not a `DOMString`, abort these steps.

That will keep the semantics in Web IDL, but also keep with the goal of never producing an observable-from-calling-script result (like rethrowing an exception).

**Comment by JosephPecoraro** [comment]
I'm not sure I agree with the idea of swallowing exceptions. That can probably move to a new issue, or continue to be discussed here.

Swallowing exceptions doesn't solve the idea of never producing observable results, because the `toString` method could just produce a side-effect (increment a counter) and therefore be "observable".

I think swallowing a `RangeError: Maximum call stack size exceeded.` exception would hide a problem instead of informing the developer there is an issue.

Are there any examples of other APIs that swallow exceptions?

**Comment by domenic** [comment]
> Swallowing exceptions doesn't solve the idea of never producing observable results, because the toString method could just produce a side-effect (increment a counter) and therefore be "observable".

Good point. I think that's part of why I'm advocating the type-check idea; never do a ToString coercion, because it can produce observable side effects.

**Comment by andysterland** [comment]
It's tough. I don't think we ever hoped to eliminate the observer effect. That's just not possible as developers can always find creative ways to cause problems like having a `get` that isn't idempotent etc. Really we just wanted to make it so that developers can stay on a happy path where their `console.*` code isn't going to cause them problems when they ship it to their customers. Indeed in a few cases we, in Web IDL, implement some no-op functions that never work with or without the tools. As we've seen plenty of cases where developers ship code that uses a feature only in some browsers like `console.table` and then, of course, it blows up in Edge.

To go back a few points I will saying that having the `console.*` defined as Web IDL when there are no tools is very usefully as it create a clear type system. Back in IE10 we had no end of problems as the console was a native COM object and folk would expect `console.log` to be defined as a function when in IE10 it was actually an `object` etc. That was a huge source of pain points. So their is a lot of value of having a clear type system so that code can interact it with it in a predictable, consistent, way across different platforms. Especially for the case where the code is running in production environments and features of the console are being detected (maybe even polyfilled).

**Comment by paulirish** [comment]
> /cc @ak239 @paulirish from Blink and @bgrins from Gecko to see if they're OK with aligning on optional DOMString label = "default" for time()/timeEnd(). 

Yup. I prefer this behavior myself and I always forget to put a label.

**Comment by JosephPecoraro** [comment]
Got this into WebKit today. [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=157325), [WebKit r200400](http://trac.webkit.org/changeset/200400)

**Comment by JosephPecoraro** [comment]
I think the discussion about reducing bad effects (swallowing exceptions, or avoiding type coercion) should probably move to its own issue with someone laying out the pros and cons and issuing a proposal. It would have ramifications beyond just `console.time`. The lists from @domenic and @andysterland are good starting points.

**Comment by ak239** [comment]
With last landed CL Chromium ToT supports default argument for console.time / console.timeEnd.

**Comment by paulirish** [comment]
> With last landed CL Chromium ToT supports default argument for console.time / console.timeEnd.

Ayup. https://codereview.chromium.org/1951773002/ just landed. Will be in tomorow's Canary.

**Comment by terinjokes** [comment]
@JosephPecoraro Do you see similar defaults for count and the grouping methods?

**Comment by JosephPecoraro** [comment]
@terinjokes No.

* `console.count()` with no arguments has special behavior that is not matched by `console.count(label)`. Without arguments it is a unique counter for its location. With a label it is not unique, and multiple locations can increment the same value. That said, ultimately I will file bugs on no-argument count, because the current `console.count()` behavior of (source:line) is out dated and useless in minified code. It should be (source:line:column). I'll file a bug about this now...

* I think an unnamed group is fine. It gives developer tools the latitude to provide their own default (localizable) name for the group in their UI. Funny, no tools do that right now! I'll fix that up in WebKit.

**Comment by terinjokes** [comment]
* Doesn't look like the current behavior is documented here. I'm happy to document it while you're opening the issue.
* Seems reasonable, I can also create a PR to fill in the group sections. :+1: for localization
