### ISSUE TITLE
Investigate optional feature support advertisement 

### ISSUE THREAD

**Issue by terinjokes** [whatwg/console#6]

**Comment by robertkowalski** [comment]
If I interpret the title right I think the support for the format specifiers 

``` 
%o     Displays as expandable DOM element
%O    Displays as expandable JS Object
%c     Applies provided CSS
```

should be optional. The expandable elements are difficult to realise in a terminal, e.g. for platforms like Node.js. Basically the same applies to the CSS styling which is just partly possible (colors would be possible)

**Comment by robertkowalski** [comment]
@terinjokes ping

**Comment by robertkowalski** [comment]
did i understand intention of the title properly?

**Comment by terinjokes** [comment]
Yes, I believe so.

I think the idea was that the JS would be able to see that expandable elements aren't possible and pick a different way to long, but maybe that's just too complicated.

**Comment by domfarolino** [comment]
I feel like a lot of the text in https://console.spec.whatwg.org/#printer (specifically user experience innovation and common object formats) allows for optional feature support, which is referenced in the https://console.spec.whatwg.org/#formatting-specifiers table. I think I'll add a note in https://github.com/whatwg/console/issues/98 so that we know to mention in some capacity, that the application of styles are up to the implementation and then close this out.
