### ISSUE TITLE
Should console.debug() be deprecated?

### ISSUE THREAD

**Issue by BurtHarris** [whatwg/console#67]
The function `console.debug()` is not present in some environments, e.g. Node.js, and according to [whatwg](https://console.spec.whatwg.org/#debug), [MSDN](https://msdn.microsoft.com/en-us/library/hh696634.aspx) and [Chrome](https://developers.google.com/web/tools/chrome-devtools/console/console-reference#debug) documentation, it duplicates the functionality of `console.log()`.  Compare with the [Node console](https://nodejs.org/api/console.html) documentation which makes no mention of `debug()`.

Thus `console.debug()` seems to serve no useful function.  See also Microsoft/TypeScript#11751.

**Comment by BurtHarris** [comment]
See also http://caniuse.com/#search=console

**Comment by domenic** [comment]
It seems more useful to ensure all environments follow the standard and include it, than risk breaking pages by removing it.

**Comment by BurtHarris** [comment]
To be clear, I didn't say it should be **removed** from any browser.   I'm suggesting it be [deprecated](http://www.oxfordlearnersdictionaries.com/definition/english/deprecate) in documentation.

**Comment by domenic** [comment]
Deprecation for web features isn't really an interesting concept. Sometimes we deprecate features that are hamful to the platform, such as appcache or showModalDialog, as a prelude to removing them a few years down the line. But we don't deprecate things just because they're redundant; if we did that half of all web APIs would be deprecated. Instead we codify them into the standard to make it clear what is usable by developers and should be implemented by browsers.

**Comment by BurtHarris** [comment]
Per the whatwg FAQ, "[Removing features is a critical part of spec development](https://wiki.whatwg.org/wiki/FAQ#Is_there_a_process_for_removing_bad_ideas_from_a_specification.3F)".    Over time, we've deprecated lots of web features, e.g. tags like `<blink>` and `<keygen>`.

**Comment by domenic** [comment]
Yep. And we do that for good reason, e.g. blink being harmful to user experience and keygen being harmful to security. In each case it was a multi-year process where we had to get all implementers on board. What is the argument against console.debug that makes it similarly harmful?
