### ISSUE TITLE
Proper behavior for string conversions

### ISSUE THREAD

**Issue by jsinmotion** [whatwg/console#80]
```
console.log("%s", {toString:function() { return "foo"; }})
```

Chrome prints `Object` whereas the spec seems to suggest `foo` is the correct response

**Comment by terinjokes** [comment]
If my understanding of EMCA's `ToString` is correct, it would be calling the object's `toString` (if defined) during `OrdinaryToPrimitive`. This specification defines formatting `%s` as calling `ToString`.

This looks like it should be filed as Chrome bug. And maybe add it to https://github.com/whatwg/console/blob/master/NOTES.md as a known bug in the meantime.

**Comment by domenic** [comment]
In general when filing issues like this, you need to ask yourself if it's a browser bug or a spec bug. The best way to go is to test all five relevant environments (four browsers + Node) and compile a table. If a majority disagree with the spec, it's probably a spec bug. But if there's no such interop, then it's browser bugs you should be filing.

**Comment by terinjokes** [comment]
Seems 

| Browser | Output |
|---------|---------|
| Chrome | `Object` |
| Firefox | `"foo"` |
| Safari 10 | `Object` |
| Edge | `"foo"` |
| Node.js | `"foo"` |

**Comment by jsinmotion** [comment]
Thanks @terinjokes i was just in the process of testing when you posted it :D 

@domenic in this case, intuition would suggest that the right thing to do is call the toString, in which case chrome and safari are the outliers.  How would we file bugs with them?

**Comment by domenic** [comment]
@jsinmotion good question! https://github.com/heycam/webidl#breaking-changes-should-be-filed-against has some links; we should probably transport them to this repo's readme too.

**Comment by JosephPecoraro** [comment]
This seems to me like another potential side effect question. This reminds me of part of @andysterland's https://github.com/whatwg/console/issues/54#issuecomment-216625533 where he said (and reiterates later):

> Though perhaps Edge/IE is unique and the Web IDL is used to define what happens when the tools aren't open.

The WebIDL-ish definition of log is currently `void log(any... data)`. That definition doesn't say to coerce any values to strings. However the description of how to handle `console.log` invokes an algorithm which performs actions on the values, and those actions could trigger side effects.

The Safari/WebKit behavior you are seeing above is because we aren't causing side effects. We capture the values provided, and later resolve the format string later on in a way that doesn't trigger side effects. I don't have the ability to test on Edge right now, but given their past comments, and their [documentation](https://msdn.microsoft.com/library/hh772179.aspx) hinting at a `void log(DOMString message, any... data)` implementation, I'd be interested in their behavior when their developer tools are open / closed for:

```js
let global = 10;
console.log("%s", {toString() { global = 999; return "foo"; }});
setTimeout(function() { console.log(global); }, 100);
```

Firefox is funny here in that without the `setTimeout` it produces `"foo"` and `10` but ultimately it did change `global` to `999`. I don't quite know what to think of that behavior.

---

My current thinking is that given how well defined the Console APIs are becoming, it would not be unreasonable to have these side effects assuming they:

1. Would not surprise a developer
1. Can be made consistent across environments

I think calling a Console API should have the same observable behavior whether or not developer tools are available or not. Cases where WebIDL requires type coercion easily satisfies the above rules. In this case, I think that having a format string causing type coercion on other arguments would not surprise a developer, so it would be acceptable.
