### ISSUE TITLE
Wanted: elide Chrome logging non 2xx resources

### ISSUE THREAD

**Issue by rektide** [whatwg/console#82]
Presently, Chrome logs any >2xx resource request (at least those issued via XHR and fetch) to console as an error. I tried adding `window.onerror= function(e){ debugger; e.preventDefault() }` to try to preempt & catch this behavior but the breakpoint never trips and there appears to be no way to prevent this error.

I'd opened https://github.com/whatwg/fetch/issues/428 thinking perhaps fetch could/should deal with this by creating some new flag for fetch to indicate that it was ok if the request failed, and to not forcibly/always log to console. Spec authors there indicated it was not in fetch's hands.

I've just opened https://bugs.chromium.org/p/chromium/issues/detail?id=677599 with Chromium since it appears to be chiefly a Chrome behavior. Firefox does not log forcibly log errors. I don't own the OSes that Safari or Edge run on so I'm not sure if I have a way to test those browsers.

As per annevk's mention in fetch#428, I do think this is perhaps something Console might be cut out to deal with. This seems like a highly unspecified use of console, and console could perhaps designate some generals ways for developers to better control browser's undesignated behavior. I thought the onerror handler I specified in my first paragraph should have done something, for example, given that Chrome was marking what was happening as an error in my console.

**Comment by JosephPecoraro** [comment]
This doesn't sound like a Console or Fetch spec issue to me. Browser engines may choose to log warnings / errors to the developer tools console in order to inform developers of potential issues. I don't think it would be worthwhile to specify every single case where a browser MAY want to log a warning or error to the console, and this particular case doesn't feel important enough to warrant such a note.

It sounds like this may be a case of a falsely reported browser generated warning and if so the Chrome bug you've filed is enough to get it addressed.

**Comment by domfarolino** [comment]
Going to go ahead and close this as per the previous comment.
