### ISSUE TITLE
Add console.countReset?

### ISSUE THREAD

**Issue by domenic** [whatwg/console#89]
Edge has a method `console.countReset(label)` which allows resetting a counter. This seems useful, and in general it's better to add console methods than remove them, in my opinion.

If we spec this we should make sure that its behavior with no arguments, or undefined, is the same as that is decided for `console.count()`. (For that, see #88.)

**Comment by domfarolino** [comment]
I'm assuming we need some more interest since Edge is the only implementer of this if I'm not mistaken? @JosephPecoraro what do you think about possibly implementing this?

And as far as behavior goes, what should `console.countReset()` do?

 - Clear the default label
 - Clear *all* labels

I can see either being valid, but I lean toward the first?

**Comment by jasnell** [comment]
Just to weigh in here, this would be tremendously useful for Node.js if we were to land the implementation of `console.count()` there. @domenic has already linked the relevant PR above. The key concern in Node.js would be `console.count()` becoming the source of memory leaks if we don't have the ability to reset the counters.

**Comment by jasnell** [comment]
@domfarolino ... in edge, `console.countReset()` only resets the default label so that's likely how it should be defined in the standard. I can see an argument for adding either a `console.countResetAll()` or even a `console.countReset(console.AllCounters)` where `console.AllCounters` is a `Symbol` but that's purely speculative and of marginal value.

**Comment by ak239** [comment]
FYI: in current Chrome implementation, console.clear clears all stored messages from internal storage including any counters or timers.

**Comment by domenic** [comment]
Oh interesting; we should investigate if other browsers do that, and if so, include it in the spec.

**Comment by jasnell** [comment]
@ak239 ... is that a recent fix in Chrome? I just tested locally and as of `58.0.3029.81`, calling `console.clear()` has no effect on the `console.count()` counters.

**Comment by ak239** [comment]
@jasnell  please check Canary. I think it was regressed a long time ago and we just fixed it back, we can revert this change but it looks good to me.

**Comment by jasnell** [comment]
Ok, if the spec is updated to have `console.clear()` clear the counters and timers, I will make sure to add that the Node.js impl. That said, I still believe `console.countReset()` is still a good idea.

**Comment by bakulf** [comment]
Firefox doesn't cancel timers nor counts. To me console.clear() should just about cleaning console messages. I prefer console.countReset(optional DOMString label = "default");

**Comment by fmartin5** [comment]
Node.js does implement `console.countReset([label='default'])` as of v8.3.

**Comment by domfarolino** [comment]
Thanks @fmartin5. Looks like we should spec it then, I'm in favor of this, with default behavior being the same as `console.count()/console.count(undefined)` etc. I can file browser bugs for this soon.

I think the issue of `console.clear()` clearing other data (like timers and counts) should be a separate issue.

**Comment by domfarolino** [comment]
Thanks all! The standard has now been updated with this method :)

**Comment by nchevobbe** [comment]
For the record, this is now implemented in Firefox 62.0a1 (2018-05-25)
